### ISSUE TITLE
Missing Geany Plugins

### ISSUE THREAD

**Issue by kafran** [flathub/org.geany.Geany#1]
The Geany Plugins are missing. Geany without plugins is useless.

**Comment by TingPing** [comment]
The repo full of plugins btw: https://github.com/geany/geany-plugins

It is probably reasonable to package most of them, they are disabled by default and few should have any big dependencies or anything.

**Comment by kafran** [comment]
SpellCheck and LineOperations are a must have.

**Comment by prcastro** [comment]
I would welcome a PR for this feature. It should be basically add `geany-plugins` to the sources, I think. Of course it would have to be tested locally, but the needed changes are minimal.

**Comment by kafran** [comment]
What's a PR? Is this fixed? How are you guys using geany without plugins?

**Comment by btreut** [comment]
What is the current state with this issue? I arrived here after searching desperately for a flatpacked version of the geany-plugins.

**Comment by TingPing** [comment]
@btreut Somebody opened a draft PR (linked above) but didn't finish it. Feel free to pick it up and submit a patch.

**Comment by btreut** [comment]
@TingPing I fear that I am not knowledgeable enough to do that.

**Comment by HugLifeTiZ** [comment]
Okay, so I decided to revisit this since Geany 2.0 came out. After adding just the tarball to the manifest, most of the plugins do appear. The ones that are missing, and what they depend on, are:

* geanygendoc
  *  CTPL
* geanylua
  * Lua, of course. (Shared module available for this.)
* geniuspaste
  * libsoup (Shared module for this too.)
* gitchangebar
  * libgit2
* markdown
  * webkitgtk, with its own deps listed further down
* spellcheck
  * enchant
* webhelper
  * webkitgtk, which itself wants...
    * unifdef
    * libwpe
    * libsoup (good thing for that shared module...)
* workbench
  * Can't tell what it wants.

The readme mentions a gtkspell plugin that doesn't exist in the source tree anymore, and a peg-markdown plugin that seems like it might just be an alternative backend for the markdown plugin.

WebkitGTK by itself makes everything so much more of a pain that I split its part of the manifest off into its own file. And then I ended up splitting the geany plugins module itself into its own file since I figured I might as well. Now I have to wait three million years for WebkitGTK itself to build to see if this venture worked.

If it all works out okay, I am perfectly okay with bundling geany-plugins with this Flatpak if the rest of you are. It may be more technically correct to make extensions, but [have you seen how many plugins there are?](https://plugins.geany.org/) Doing it correctly seems like a gargantuan undertaking that will make this package considerably more of a pain to maintain.

**Comment by btreut** [comment]
@HugLifeTiZ thanks a lot. Sorrily, I do not remember which plugin I missed in March. 
Is your plugin flatpak meant for Geany 2 or 1.38 and is it available from standard flathub or from some test repo?

**Comment by HugLifeTiZ** [comment]
I'm not done with it yet. As it stands, it will not be a separate Flatpak installation, it will just be included in the regular Flatpak package. All the plugins install as library files inside `/app/lib/geany`, so I'm not sure if there's a good way to separate them out that fits with Flatpak's extension system. And that's presuming they don't ship any extra data. It may be controversial to make Geany suddenly grow the size of WebkitGTK + extras, but the niche of specifically minimalistic GTK3 editors is fulfilled by Mousepad already, so it makes sense to pivot Geany into the niche of a highly extensible GTK3 editor, where it was meant to be all along anyways.

If there is in fact a clean way to do this with the extension system, I'd be willing to do it that way.

But it's all moot because I'm tripping on the plugins that depend on WebkitGTK anyways (markdown and webhelper). I spend roughly 3 million years building WebkitGTK only for those two plugins to still not appear. I have to try and figure out why that is. But I'd rather ship Geany-Plugins without WebkitGTK than not ship it at all, so I'm only gonna give myself a little time for that.

**Comment by btreut** [comment]
thanks a lot. Looks good, compared to 6 days ago I see now lots of plugins in the plugin manager

**Comment by HugLifeTiZ** [comment]
No problem. I found out that three of them are still not working for various reasons, and I've been working on fixing it. (WebkitGTK takes forever to build.) I'll push out a new version soon with *all* plugins available.

**Comment by tim77** [comment]
> WebkitGTK takes forever to build doesn't help much?

```bash
flatpak run org.flatpak.Builder --ccache
```

**Comment by HugLifeTiZ** [comment]
> > WebkitGTK takes forever to build doesn't help much?
> 
> ```shell
> flatpak run org.flatpak.Builder --ccache
> ```

Wait, it doesn't do that by default? That's weird. Thanks for the tip!

**Comment by TingPing** [comment]
> Wait, it doesn't do that by default? That's weird.

Well if you aren't constantly rebuilding from the same builddir you are just wasting space. WebKit is one of the few places it would be really helpful.
