### ISSUE TITLE
Cannot run Python code directly from within Geany

### ISSUE THREAD

**Issue by unholyeyebrows** [flathub/org.geany.Geany#4]
Linux distribution and version:
Fedora 28 x64

Flatpak version:
Flatpak 1.0.1

Description of the problem
I can edit a program in Geany - I'm using Python as an example - but when I come to execute it from within Geany then I receive an error when I should instead be seeing my code run.

Steps to reproduce
Install Geany:
flatpak install org.geany.Geany

Launch Geany from Gnome lanucher, then...

Edit the build commands as follows:
Compile: python3 -m py_compile "%f"
Execute: python3 "%f"

Write some Python code and save it as hello_world.py:
print("Hello Python world!")

Compile by pressing F8. This works:
python3 -m py_compile "hello_world.py" (in directory: /home/nharvey/Documents/Python/Hello World)
Compilation finished successfully.

Attempt to execute by pressing F5 and this fails with:
16:13:32: Cannot execute build command "xterm -e "/bin/sh /tmp/geany_run_script_DT1YOZ.sh"": No such file or directory. Check the Terminal setting in Preferences

The Geany terminal command in Preferences is as per the defaults:
xterm -e "/bin/sh %c"

Of course, this can be worked-around by running my edited Python code from a terminal but this is an inefficient workflow and Geany should be able to run the code directly. This problem does not exists when installing Geany from the RPM so I'm assuming for now this is a Flatpak issue. Any ideas would be appreciated.

**Comment by TingPing** [comment]
> The Geany terminal command in Preferences is as per the defaults:
> xterm -e "/bin/sh %c"

Sounds to me that default should just be patched to be `/bin/sh %c`. Not sure why hardcoding `xterm` would ever be a good idea.

**Comment by b4n** [comment]
It should be `whichever-is-your-favorite-terminal-app executeflag "/bin/sh %c"`, so it spawns the terminal app and runs the command in it.  Alternatively, use the setting to run in the embedded terminal.

The thing is that the favorite terminal app is not something that is easy to select arbitrarily, and `xterm` was selected as default probably because it used to be kind of the canonical X terminal emulator.
Depending on the distribution, there are other more reasonable defaults, like on Debian using the virtual `x-terminal-emulator` is better, but it's not something that works everywhere.

I'm not sure there's a perfect solution here, unless this distribution has a more specific target (GNOME, MATE, KDE, etc.) where we can expect some specific terminal app.

**Comment by TingPing** [comment]
Nah, Flathub is distro agnostic so it can't assume any host tools.

**Comment by b4n** [comment]
I see it depends on `gnome-sdk`, but indeed I wouldn't imagine this to bring `gnome-terminal`.
So I guess a solution could be changing the default setting to run programs in the integrated terminal emulator (if the flatpack has the correct libvte, as it's a soft dep), or keep on depending on the user having or configuring the terminal tool.

**Comment by TingPing** [comment]
VTE is in the runtime.

**Comment by TiZ-HugLife** [comment]
Closing this because this is basically the same as #14.

**Comment by fastrizwaan** [comment]
https://github.com/flathub/org.geany.Geany/issues/14#issuecomment-2326148180
